name: pokedexx_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1

  cached_network_image: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

 assets: 
   - images/

 uses-material-design: true

